#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Oct 20 10:50:53 2017

@author: es3017
"""

## I want to reproduce Figure4 of Weller Primer
## CTCS VS FTBS vs ANALYTIC
## for periodic domain , nt = 100, nx = 40 , Lx= 1 , 
## c = 0.2 
## NON SMOOTH CI   U0(x)= 0.5 ( 1- cos (4pix) ) for x<=0.5
##                 U0(x) = 0 elsewhere )


import numpy as np
import matplotlib.pyplot as plt
from numpy import where, cos, pi , sin


def main():
    
    
    # FTBS scheme with periodic boundaries 
    def FTBS ( phi0, c , nt): 
        
        if (phi0[0] != phi0[-1]):
            print('Careful: your c.i. PhiO does not have periodic boundaries')
            
        nx = len(phi0) 
        # Create the function phi(t) and initialize to 0
        phi = np.zeros(nx,dtype=float) 
        # Create phiOld and initialize it to phi0
        phiOld = phi0.copy()
        
        # Loop over time steps
        for it in range(nt):
            # Loop over space (excluding end points, [0] and [nx-1])
            for ix in range(1,nx-1):
                phi[ix] = phiOld[ix] - c * (phiOld[ix] - phiOld[ix-1])
            # Update values at end points
            phi[0] = phiOld[0] - c * (phiOld[0] - phiOld[nx-2])
            phi[nx-1] = phi[0]
            # Update old time value
            phiOld = phi.copy() 
            
            
        return(phi)
        
    # CTCS scheme with periodic boundaries 
    def CTCS ( phi0, c , nt): 
        
        if (phi0[0] != phi0[-1]):
            print('Careful: your c.i. PhiO does not have periodic boundaries')
            
        nx = len(phi0) 
        # Create the function phi(t) and initialize to 0
        phi = np.zeros(nx,dtype=float) 
        # Create phiOld and initialize it to phi0
        phiOld2 = phi0.copy()
        
        # For CTCS you need also to initialize phi1 
        # Create phiOld1 and initialize it to phi1=f (phi0) 
        # via FTCS
        phiOld1 = np.zeros(nx,dtype=float)
        for ix in range(1, nx-1):
            phiOld1[ix] = phiOld2[ix] - 0.5 * c * (phiOld2[ix+1] - phiOld2[ix-1])
        # Update values at end points ([0] and [nx-1])
        phiOld1[0] = phiOld2[0] -  0.5 * c * (phiOld2[1] - phiOld2[nx-2])
        phiOld1[nx-1] = phiOld1[0]
        
        # Loop over time steps t = 2,..(nt-1)  (total of nt-2 elements)
        for it in range(2,nt):  
            # Loop CTCS over space (excluding end points)
            for ix in range(1,nx-1):
                phi[ix] = phiOld2[ix] - c * ( phiOld1[ix+1] - phiOld1[ix-1] )
            # Update values at end points
            phi[0] = phiOld2[0] -  c * (phiOld1[1] - phiOld1[nx-2])
            phi[nx-1] = phi[0]
            # Update old time value 
            phiOld2 = phiOld1.copy()
            phiOld1 = phi.copy()
            
            
        return(phi)
        
    # Set the space grid
    Nx = 40                    # Number of points from x=0 to x=1 inclusive
    Length=1
    x = np.linspace(0,Length,Nx)     # Points in the x direction
    
    # Initial conditions for dependent variable phi 
    f_0 = where(x<0.5, 0.5*(1-cos(4*pi*x)),0 )
    # Plot initial conditions
    plt.clf()
    plt.ion()
    plt.plot(x, f_0, label="Initial conditions")
    plt.legend(loc="best")
    plt.axhline(0, linestyle=':',color='black')
    plt.ylim([-0.2,1.2])
    plt.show()
    
    Nt = 100
    c = 0.2
    
    # Call CTCS and FTBS
    
    f_FTBS = FTBS (f_0, c, Nt)
    f_CTCS = CTCS (f_0, c, Nt)
    
    # Plot result
    plt.clf()
    plt.ion()
    plt.plot(x, f_FTBS, label="FTBS at t=%g" %Nt )
    plt.plot(x, f_CTCS, label="CTCS at t=%g" %Nt )
    plt.legend(loc="best")
    plt.title("FTBS vs CTCS scheme for Linear Advection, Courant c = %g" %c)
    plt.axhline(0, linestyle=':',color='black')
    plt.ylim([-0.2,1.2])
    plt.show()
    
main()