#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Nov  8 16:09:46 2017

@author: es3017
"""

import numpy as np
import matplotlib.pyplot as plt
from numpy import where, cos, pi , sin


import InitialConditions
import grid
import Analytical 
import CTCSAlone
import CTBSAlone
import FTCSAlone

def main():
    ## Declare an instance of the Grid class, called grid which    ###
    ## defines the grid for these simulations. Thus grid.dx and    ###
    ## grid.x will automatically be defined
    grid = Grid( 100 , 1.0 )

    plt.plot( grid.x , grid.x)
    plt.show()    
    
    
    

    
    
    
    
main()